/**
 * Created by lxj on 2/7/2015.
 */

export default DS.Transform.extend({
    mapping : [
        { id :"Aiguo Rd", text :"Aiguo Rd"},
        { id :"Anshan Xincun", text :"Anshan Xincun"},
        { id :"Anting", text :"Anting"},
        { id :"Baiyin Rd", text :"Baiyin Rd"},
        { id :"Bao'an Highway", text :"Bao'an Highway"},
        { id :"Baoshan Rd", text :"Baoshan Rd"},
        { id :"Baoyang Rd", text :"Baoyang Rd"},
        { id :"Beiqiao", text :"Beiqiao"},
        { id :"Beixinjing", text :"Beixinjing"},
        { id :"Beiyangjing Rd", text :"Beiyangjing Rd"},
        { id :"Boxing Rd", text :"Boxing Rd"},
        { id :"Caobao Rd", text :"Caobao Rd"},
        { id :"Caohejing Hi-Tech Park", text :"Caohejing Hi-Tech Park"},
        { id :"Caoxi Rd", text :"Caoxi Rd"},
        { id :"Caoyang Rd", text :"Caoyang Rd"},
        { id :"Century Avenue", text :"Century Avenue"},
        { id :"Century Park", text :"Century Park"},
        { id :"Changshou Rd", text :"Changshou Rd"},
        { id :"Changshu Rd", text :"Changshu Rd"},
        { id :"Changzhong Rd", text :"Changzhong Rd"},
        { id :"Chengshan Rd", text :"Chengshan Rd"},
        { id :"Chifeng Rd", text :"Chifeng Rd"},
        { id :"China Art Museum", text :"China Art Museum"},
        { id :"Chuansha", text :"Chuansha"},
        { id :"Chunshen Rd", text :"Chunshen Rd"},
        { id :"Dabaishu Rd", text :"Dabaishu Rd"},
        { id :"Dachang Town", text :"Dachang Town"},
        { id :"Daduhe Rd", text :"Daduhe Rd"},
        { id :"Dahua San Rd", text :"Dahua San Rd"},
        { id :"Dalian Rd", text :"Dalian Rd"},
        { id :"Damuqiao Rd", text :"Damuqiao Rd"},
        { id :"Dapuqiao", text :"Dapuqiao"},
        { id :"Dashijie", text :"Dashijie"},
        { id :"Deping Rd", text :"Deping Rd"},
        { id :"Dishui Lake", text :"Dishui Lake"},
        { id :"Dong'an Rd", text :"Dong'an Rd"},
        { id :"Dongbaoxing Rd", text :"Dongbaoxing Rd"},
        { id :"Dongchang Rd", text :"Dongchang Rd"},
        { id :"Dongchuan Rd", text :"Dongchuan Rd"},
        { id :"Dongjing Rd", text :"Dongjing Rd"},
        { id :"Dongjing", text :"Dongjing"},
        { id :"Donglu Rd", text :"Donglu Rd"},
        { id :"Dongming Rd", text :"Dongming Rd"},
        { id :"East Changji Rd", text :"East Changji Rd"},
        { id :"East Hangtou", text :"East Hangtou"},
        { id :"East Huaxia Rd", text :"East Huaxia Rd"},
        { id :"East Huinan", text :"East Huinan"},
        { id :"East Nanjing Rd", text :"East Nanjing Rd"},
        { id :"East Sanlin", text :"East Sanlin"},
        { id :"East Xujing", text :"East Xujing"},
        { id :"East Yingao Rd", text :"East Yingao Rd"},
        { id :"East Zhoupu", text :"East Zhoupu"},
        { id :"Fanghua Rd", text :"Fanghua Rd"},
        { id :"Fengqiao Rd", text :"Fengqiao Rd"},
        { id :"Fengzhuang", text :"Fengzhuang"},
        { id :"Fujin Rd", text :"Fujin Rd"},
        { id :"Fuxing Island", text :"Fuxing Island"},
        { id :"Gangcheng Rd", text :"Gangcheng Rd"},
        { id :"Gaoqing Rd", text :"Gaoqing Rd"},
        { id :"Gongfu Xincun", text :"Gongfu Xincun"},
        { id :"Gongkang Rd", text :"Gongkang Rd"},
        { id :"Guanglan Rd", text :"Guanglan Rd"},
        { id :"Guangming Rd", text :"Guangming Rd"},
        { id :"Gucun Park", text :"Gucun Park"},
        { id :"Guilin Rd", text :"Guilin Rd"},
        { id :"Guoquan Rd", text :"Guoquan Rd"},
        { id :"Hailun Rd", text :"Hailun Rd"},
        { id :"Haitiansan Rd", text :"Haitiansan Rd"},
        { id :"Hangjin Rd", text :"Hangjin Rd"},
        { id :"Hangzhong Rd", text :"Hangzhong Rd"},
        { id :"Hanzhong Rd", text :"Hanzhong Rd"},
        { id :"Hechuan Rd", text :"Hechuan Rd"},
        { id :"Hengshan Rd", text :"Hengshan Rd"},
        { id :"Heshahangcheng", text :"Heshahangcheng"},
        { id :"Hongkou Football Stadium", text :"Hongkou Football Stadium"},
        { id :"Hongqiao Airport Terminal 1", text :"Hongqiao Airport Terminal 1"},
        { id :"Hongqiao Airport Terminal 2", text :"Hongqiao Airport Terminal 2"},
        { id :"Hongqiao Railway Station", text :"Hongqiao Railway Station"},
        { id :"Hongqiao Rd", text :"Hongqiao Rd"},
        { id :"Houtan", text :"Houtan"},
        { id :"Huamu Rd", text :"Huamu Rd"},
        { id :"Huangxing Park", text :"Huangxing Park"},
        { id :"Huangxing Rd", text :"Huangxing Rd"},
        { id :"Huaning Rd", text :"Huaning Rd"},
        { id :"Huaqiao", text :"Huaqiao"},
        { id :"Huaxia Middle Rd", text :"Huaxia Middle Rd"},
        { id :"Huinan", text :"Huinan"},
        { id :"Hulan Rd", text :"Hulan Rd"},
        { id :"International Cruise Terminal", text :"International Cruise Terminal"},
        { id :"Jiading Xincheng", text :"Jiading Xincheng"},
        { id :"Jianchuan Rd", text :"Jianchuan Rd"},
        { id :"Jiangpu Park", text :"Jiangpu Park"},
        { id :"Jiangpu Rd", text :"Jiangpu Rd"},
        { id :"Jiangsu Rd", text :"Jiangsu Rd"},
        { id :"Jiangwan Stadium", text :"Jiangwan Stadium"},
        { id :"Jiangwan Town", text :"Jiangwan Town"},
        { id :"Jiangyue Rd", text :"Jiangyue Rd"},
        { id :"Jiaotong University", text :"Jiaotong University"},
        { id :"Jiashan Rd", text :"Jiashan Rd"},
        { id :"Jing'an Temple", text :"Jing'an Temple"},
        { id :"Jinhai Rd", text :"Jinhai Rd"},
        { id :"Jinjiang Park", text :"Jinjiang Park"},
        { id :"Jinjing Rd", text :"Jinjing Rd"},
        { id :"Jinke Rd", text :"Jinke Rd"},
        { id :"Jinping Rd", text :"Jinping Rd"},
        { id :"Jinqiao Rd", text :"Jinqiao Rd"},
        { id :"Jinshajiang Rd", text :"Jinshajiang Rd"},
        { id :"Jinxiu Rd", text :"Jinxiu Rd"},
        { id :"Jinyun Rd", text :"Jinyun Rd"},
        { id :"Jiuting", text :"Jiuting"},
        { id :"Jufeng Rd", text :"Jufeng Rd"},
        { id :"Lancun Rd", text :"Lancun Rd"},
        { id :"Langao Rd", text :"Langao Rd"},
        { id :"Laoximen", text :"Laoximen"},
        { id :"Lianhang Rd", text :"Lianhang Rd"},
        { id :"Lianhua Rd", text :"Lianhua Rd"},
        { id :"Lingang Avenue", text :"Lingang Avenue"},
        { id :"Lingkong Rd", text :"Lingkong Rd"},
        { id :"Lingzhao Xincun", text :"Lingzhao Xincun"},
        { id :"Linping Rd", text :"Linping Rd"},
        { id :"Linyi Xincun", text :"Linyi Xincun"},
        { id :"Liuhang", text :"Liuhang"},
        { id :"Liziyuan", text :"Liziyuan"},
        { id :"Longbai Xincun", text :"Longbai Xincun"},
        { id :"Longcao Rd", text :"Longcao Rd"},
        { id :"Longchang Rd", text :"Longchang Rd"},
        { id :"Longde Rd", text :"Longde Rd"},
        { id :"Longhua", text :"Longhua"},
        { id :"Longxi Rd", text :"Longxi Rd"},
        { id :"Longyang Rd", text :"Longyang Rd"},
        { id :"Longyao Rd", text :"Longyao Rd"},
        { id :"Loushanguan Rd", text :"Loushanguan Rd"},
        { id :"Luban Rd", text :"Luban Rd"},
        { id :"Luheng Rd", text :"Luheng Rd"},
        { id :"Lujiabang Rd", text :"Lujiabang Rd"},
        { id :"Lujiabang", text :"Lujiabang"},
        { id :"Lujiazui", text :"Lujiazui"},
        { id :"Luonan Xincun", text :"Luonan Xincun"},
        { id :"Luoshan Rd", text :"Luoshan Rd"},
        { id :"Madang Rd", text :"Madang Rd"},
        { id :"Malu", text :"Malu"},
        { id :"Meilan Lake", text :"Meilan Lake"},
        { id :"Middle Chuangxin Rd", text :"Middle Chuangxin Rd"},
        { id :"Middle Yanggao Rd", text :"Middle Yanggao Rd"},
        { id :"Middle Yanji Rd", text :"Middle Yanji Rd"},
        { id :"Minhang Development Zone", text :"Minhang Development Zone"},
        { id :"Minsheng Rd", text :"Minsheng Rd"},
        { id :"Nanchen Rd", text :"Nanchen Rd"},
        { id :"Nanpu Bridge", text :"Nanpu Bridge"},
        { id :"Nanxiang", text :"Nanxiang"},
        { id :"Nenjiang Rd", text :"Nenjiang Rd"},
        { id :"Ningguo Rd", text :"Ningguo Rd"},
        { id :"North Jiading", text :"North Jiading"},
        { id :"North Jiangyang Rd", text :"North Jiangyang Rd"},
        { id :"North Sichuan Rd", text :"North Sichuan Rd"},
        { id :"North Waigaoqiao Free Trade Zone", text :"North Waigaoqiao Free Trade Zone"},
        { id :"North Xizang Rd", text :"North Xizang Rd"},
        { id :"North Yanggao Rd", text :"North Yanggao Rd"},
        { id :"North Zhongshan Rd", text :"North Zhongshan Rd"},
        { id :"Oriental Sports Center", text :"Oriental Sports Center"},
        { id :"Panguang Rd", text :"Panguang Rd"},
        { id :"Pengpu Xincun", text :"Pengpu Xincun"},
        { id :"People's Square", text :"People's Square"},
        { id :"Pudian Rd", text :"Pudian Rd"},
        { id :"Pudong Avenue", text :"Pudong Avenue"},
        { id :"Pudong International Airport", text :"Pudong International Airport"},
        { id :"Pujiang Town", text :"Pujiang Town"},
        { id :"Pusan Rd", text :"Pusan Rd"},
        { id :"Qibao", text :"Qibao"},
        { id :"Qihua Rd", text :"Qihua Rd"},
        { id :"Qilianshan Rd", text :"Qilianshan Rd"},
        { id :"Qufu Rd", text :"Qufu Rd"},
        { id :"Quyang Rd", text :"Quyang Rd"},
        { id :"Sanlin", text :"Sanlin"},
        { id :"Sanmen Rd", text :"Sanmen Rd"},
        { id :"Shangcheng Rd", text :"Shangcheng Rd"},
        { id :"Shangda Rd", text :"Shangda Rd"},
        { id :"Shanghai Children's Medical Center", text :"Shanghai Children's Medical Center"},
        { id :"Shanghai Circuit", text :"Shanghai Circuit"},
        { id :"Shanghai Circus World", text :"Shanghai Circus World"},
        { id :"Shanghai Hongqiao Railway station", text :"Shanghai Hongqiao Railway station"},
        { id :"Shanghai Indoor Stadium", text :"Shanghai Indoor Stadium"},
        { id :"Shanghai Inte. Automobile City", text :"Shanghai Inte. Automobile City"},
        { id :"Shanghai Library", text :"Shanghai Library"},
        { id :"Shanghai Railway Station", text :"Shanghai Railway Station"},
        { id :"Shanghai Science and Technology Museum", text :"Shanghai Science and Technology Museum"},
        { id :"Shanghai South Railway Station", text :"Shanghai South Railway Station"},
        { id :"Shanghai Stadium", text :"Shanghai Stadium"},
        { id :"Shanghai Swimming Center", text :"Shanghai Swimming Center"},
        { id :"Shanghai University", text :"Shanghai University"},
        { id :"Shanghai Zoo", text :"Shanghai Zoo"},
        { id :"Shangnan Rd", text :"Shangnan Rd"},
        { id :"Shendu Highway", text :"Shendu Highway"},
        { id :"Shenjiang Rd", text :"Shenjiang Rd"},
        { id :"Sheshan", text :"Sheshan"},
        { id :"Shiguang Rd", text :"Shiguang Rd"},
        { id :"Shilong Rd", text :"Shilong Rd"},
        { id :"Shuichan Rd", text :"Shuichan Rd"},
        { id :"Shuicheng Rd", text :"Shuicheng Rd"},
        { id :"Shuyuan", text :"Shuyuan"},
        { id :"Sijing", text :"Sijing"},
        { id :"Siping Rd", text :"Siping Rd"},
        { id :"Songbin Rd", text :"Songbin Rd"},
        { id :"Songfa Rd", text :"Songfa Rd"},
        { id :"Songhong Rd", text :"Songhong Rd"},
        { id :"Songjiang South Railway Station", text :"Songjiang South Railway Station"},
        { id :"Songjiang Sports Center", text :"Songjiang Sports Center"},
        { id :"Songjiang University Town", text :"Songjiang University Town"},
        { id :"Songjiang Xincheng", text :"Songjiang Xincheng"},
        { id :"Songyuan Rd", text :"Songyuan Rd"},
        { id :"South Changjiang Rd", text :"South Changjiang Rd"},
        { id :"South Huangpi Rd", text :"South Huangpi Rd"},
        { id :"South Lingyan Rd", text :"South Lingyan Rd"},
        { id :"South Qilianshan Rd", text :"South Qilianshan Rd"},
        { id :"South Shaanxi Rd", text :"South Shaanxi Rd"},
        { id :"South Shanxi Rd", text :"South Shanxi Rd"},
        { id :"South Waigaoqiao Free Trade Zone", text :"South Waigaoqiao Free Trade Zone"},
        { id :"South Xizang Rd", text :"South Xizang Rd"},
        { id :"South Yanggao Rd", text :"South Yanggao Rd"},
        { id :"Tangqiao", text :"Tangqiao"},
        { id :"Tangzhen", text :"Tangzhen"},
        { id :"Taopu Xincun", text :"Taopu Xincun"},
        { id :"Tiantong Rd", text :"Tiantong Rd"},
        { id :"Tieli Rd", text :"Tieli Rd"},
        { id :"Tilanqiao", text :"Tilanqiao"},
        { id :"Tonghe Xincun", text :"Tonghe Xincun"},
        { id :"Tongji University", text :"Tongji University"},
        { id :"Waihuan Rd", text :"Waihuan Rd"},
        { id :"Wenshui Rd", text :"Wenshui Rd"},
        { id :"West Gaoke Rd", text :"West Gaoke Rd"},
        { id :"West Huaxia Rd", text :"West Huaxia Rd"},
        { id :"West Jiading", text :"West Jiading"},
        { id :"West Jinshajiang Rd", text :"West Jinshajiang Rd"},
        { id :"West Nanjing Rd", text :"West Nanjing Rd"},
        { id :"West Railway Station", text :"West Railway Station"},
        { id :"West Yan'an Rd", text :"West Yan'an Rd"},
        { id :"West Yingao Rd", text :"West Yingao Rd"},
        { id :"West Youyi Rd", text :"West Youyi Rd"},
        { id :"Wild Animal Park", text :"Wild Animal Park"},
        { id :"Wujiaochang", text :"Wujiaochang"},
        { id :"Wulian Rd", text :"Wulian Rd"},
        { id :"Wuning Rd", text :"Wuning Rd"},
        { id :"Wuwei Rd", text :"Wuwei Rd"},
        { id :"Wuzhou Avenue", text :"Wuzhou Avenue"},
        { id :"Xiangyin Rd", text :"Xiangyin Rd"},
        { id :"Xiaonanmen", text :"Xiaonanmen"},
        { id :"Xinchang", text :"Xinchang"},
        { id :"Xincun Rd", text :"Xincun Rd"},
        { id :"Xingzhi Rd", text :"Xingzhi Rd"},
        { id :"Xingzhong Rd", text :"Xingzhong Rd"},
        { id :"Xinjiangwancheng", text :"Xinjiangwancheng"},
        { id :"Xintiandi", text :"Xintiandi"},
        { id :"Xinzha Rd", text :"Xinzha Rd"},
        { id :"Xinzhuang", text :"Xinzhuang"},
        { id :"Xujiahui", text :"Xujiahui"},
        { id :"Yanchang Rd", text :"Yanchang Rd"},
        { id :"Yangshupu Rd", text :"Yangshupu Rd"},
        { id :"Yangsi", text :"Yangsi"},
        { id :"Yaohua Rd", text :"Yaohua Rd"},
        { id :"Yili Rd", text :"Yili Rd"},
        { id :"Yindu Rd", text :"Yindu Rd"},
        { id :"Yishan Rd", text :"Yishan Rd"},
        { id :"Youdian Xincun", text :"Youdian Xincun"},
        { id :"Youyi Rd", text :"Youyi Rd"},
        { id :"Yuandong Avenue", text :"Yuandong Avenue"},
        { id :"Yuanshen Stadium", text :"Yuanshen Stadium"},
        { id :"Yunjin Rd", text :"Yunjin Rd"},
        { id :"Yunshan Rd", text :"Yunshan Rd"},
        { id :"Yuntai Rd", text :"Yuntai Rd"},
        { id :"Yuqiao", text :"Yuqiao"},
        { id :"Yuyuan Garden", text :"Yuyuan Garden"},
        { id :"Zhanghuabang", text :"Zhanghuabang"},
        { id :"Zhangjiang High Technology Park", text :"Zhangjiang High Technology Park"},
        { id :"Zhaofeng Rd", text :"Zhaofeng Rd"},
        { id :"Zhaojiabang Rd", text :"Zhaojiabang Rd"},
        { id :"Zhenbei Rd", text :"Zhenbei Rd"},
        { id :"Zhenping Rd", text :"Zhenping Rd"},
        { id :"Zhenru", text :"Zhenru"},
        { id :"Zhongchun Rd", text :"Zhongchun Rd"},
        { id :"Zhongshan Park", text :"Zhongshan Park"},
        { id :"Zhongtan Rd", text :"Zhongtan Rd"},
        { id :"Zhongxing Rd", text :"Zhongxing Rd"},
        { id :"Zhouhai Rd", text :"Zhouhai Rd"},
        { id :"Zhuanqiao", text :"Zhuanqiao"},
        { id :"Ziteng Rd", text :"Ziteng Rd"},
        { id :"Zuibaichi Park", text :"Zuibaichi Park"}
    ]
});


