/**
 * Created by lxj on 2/7/2015.
 */
import MappingTransformMixins from 'flatmate/transforms/mapping-transform-mixins';

export default DS.Transform.extend(MappingTransformMixins, {
    mapping : [
        { index:"Aiguo Rd", name:"Aiguo Rd"},
        { index:"Anshan Xincun", name:"Anshan Xincun"},
        { index:"Anting", name:"Anting"},
        { index:"Baiyin Rd", name:"Baiyin Rd"},
        { index:"Bao'an Highway", name:"Bao'an Highway"},
        { index:"Baoshan Rd", name:"Baoshan Rd"},
        { index:"Baoyang Rd", name:"Baoyang Rd"},
        { index:"Beiqiao", name:"Beiqiao"},
        { index:"Beixinjing", name:"Beixinjing"},
        { index:"Beiyangjing Rd", name:"Beiyangjing Rd"},
        { index:"Boxing Rd", name:"Boxing Rd"},
        { index:"Caobao Rd", name:"Caobao Rd"},
        { index:"Caohejing Hi-Tech Park", name:"Caohejing Hi-Tech Park"},
        { index:"Caoxi Rd", name:"Caoxi Rd"},
        { index:"Caoyang Rd", name:"Caoyang Rd"},
        { index:"Century Avenue", name:"Century Avenue"},
        { index:"Century Park", name:"Century Park"},
        { index:"Changshou Rd", name:"Changshou Rd"},
        { index:"Changshu Rd", name:"Changshu Rd"},
        { index:"Changzhong Rd", name:"Changzhong Rd"},
        { index:"Chengshan Rd", name:"Chengshan Rd"},
        { index:"Chifeng Rd", name:"Chifeng Rd"},
        { index:"China Art Museum", name:"China Art Museum"},
        { index:"Chuansha", name:"Chuansha"},
        { index:"Chunshen Rd", name:"Chunshen Rd"},
        { index:"Dabaishu Rd", name:"Dabaishu Rd"},
        { index:"Dachang Town", name:"Dachang Town"},
        { index:"Daduhe Rd", name:"Daduhe Rd"},
        { index:"Dahua San Rd", name:"Dahua San Rd"},
        { index:"Dalian Rd", name:"Dalian Rd"},
        { index:"Damuqiao Rd", name:"Damuqiao Rd"},
        { index:"Dapuqiao", name:"Dapuqiao"},
        { index:"Dashijie", name:"Dashijie"},
        { index:"Deping Rd", name:"Deping Rd"},
        { index:"Dishui Lake", name:"Dishui Lake"},
        { index:"Dong'an Rd", name:"Dong'an Rd"},
        { index:"Dongbaoxing Rd", name:"Dongbaoxing Rd"},
        { index:"Dongchang Rd", name:"Dongchang Rd"},
        { index:"Dongchuan Rd", name:"Dongchuan Rd"},
        { index:"Dongjing Rd", name:"Dongjing Rd"},
        { index:"Dongjing", name:"Dongjing"},
        { index:"Donglu Rd", name:"Donglu Rd"},
        { index:"Dongming Rd", name:"Dongming Rd"},
        { index:"East Changji Rd", name:"East Changji Rd"},
        { index:"East Hangtou", name:"East Hangtou"},
        { index:"East Huaxia Rd", name:"East Huaxia Rd"},
        { index:"East Huinan", name:"East Huinan"},
        { index:"East Nanjing Rd", name:"East Nanjing Rd"},
        { index:"East Sanlin", name:"East Sanlin"},
        { index:"East Xujing", name:"East Xujing"},
        { index:"East Yingao Rd", name:"East Yingao Rd"},
        { index:"East Zhoupu", name:"East Zhoupu"},
        { index:"Fanghua Rd", name:"Fanghua Rd"},
        { index:"Fengqiao Rd", name:"Fengqiao Rd"},
        { index:"Fengzhuang", name:"Fengzhuang"},
        { index:"Fujin Rd", name:"Fujin Rd"},
        { index:"Fuxing Island", name:"Fuxing Island"},
        { index:"Gangcheng Rd", name:"Gangcheng Rd"},
        { index:"Gaoqing Rd", name:"Gaoqing Rd"},
        { index:"Gongfu Xincun", name:"Gongfu Xincun"},
        { index:"Gongkang Rd", name:"Gongkang Rd"},
        { index:"Guanglan Rd", name:"Guanglan Rd"},
        { index:"Guangming Rd", name:"Guangming Rd"},
        { index:"Gucun Park", name:"Gucun Park"},
        { index:"Guilin Rd", name:"Guilin Rd"},
        { index:"Guoquan Rd", name:"Guoquan Rd"},
        { index:"Hailun Rd", name:"Hailun Rd"},
        { index:"Haitiansan Rd", name:"Haitiansan Rd"},
        { index:"Hangjin Rd", name:"Hangjin Rd"},
        { index:"Hangzhong Rd", name:"Hangzhong Rd"},
        { index:"Hanzhong Rd", name:"Hanzhong Rd"},
        { index:"Hechuan Rd", name:"Hechuan Rd"},
        { index:"Hengshan Rd", name:"Hengshan Rd"},
        { index:"Heshahangcheng", name:"Heshahangcheng"},
        { index:"Hongkou Football Stadium", name:"Hongkou Football Stadium"},
        { index:"Hongqiao Airport Terminal 1", name:"Hongqiao Airport Terminal 1"},
        { index:"Hongqiao Airport Terminal 2", name:"Hongqiao Airport Terminal 2"},
        { index:"Hongqiao Railway Station", name:"Hongqiao Railway Station"},
        { index:"Hongqiao Rd", name:"Hongqiao Rd"},
        { index:"Houtan", name:"Houtan"},
        { index:"Huamu Rd", name:"Huamu Rd"},
        { index:"Huangxing Park", name:"Huangxing Park"},
        { index:"Huangxing Rd", name:"Huangxing Rd"},
        { index:"Huaning Rd", name:"Huaning Rd"},
        { index:"Huaqiao", name:"Huaqiao"},
        { index:"Huaxia Middle Rd", name:"Huaxia Middle Rd"},
        { index:"Huinan", name:"Huinan"},
        { index:"Hulan Rd", name:"Hulan Rd"},
        { index:"International Cruise Terminal", name:"International Cruise Terminal"},
        { index:"Jiading Xincheng", name:"Jiading Xincheng"},
        { index:"Jianchuan Rd", name:"Jianchuan Rd"},
        { index:"Jiangpu Park", name:"Jiangpu Park"},
        { index:"Jiangpu Rd", name:"Jiangpu Rd"},
        { index:"Jiangsu Rd", name:"Jiangsu Rd"},
        { index:"Jiangwan Stadium", name:"Jiangwan Stadium"},
        { index:"Jiangwan Town", name:"Jiangwan Town"},
        { index:"Jiangyue Rd", name:"Jiangyue Rd"},
        { index:"Jiaotong University", name:"Jiaotong University"},
        { index:"Jiashan Rd", name:"Jiashan Rd"},
        { index:"Jing'an Temple", name:"Jing'an Temple"},
        { index:"Jinhai Rd", name:"Jinhai Rd"},
        { index:"Jinjiang Park", name:"Jinjiang Park"},
        { index:"Jinjing Rd", name:"Jinjing Rd"},
        { index:"Jinke Rd", name:"Jinke Rd"},
        { index:"Jinping Rd", name:"Jinping Rd"},
        { index:"Jinqiao Rd", name:"Jinqiao Rd"},
        { index:"Jinshajiang Rd", name:"Jinshajiang Rd"},
        { index:"Jinxiu Rd", name:"Jinxiu Rd"},
        { index:"Jinyun Rd", name:"Jinyun Rd"},
        { index:"Jiuting", name:"Jiuting"},
        { index:"Jufeng Rd", name:"Jufeng Rd"},
        { index:"Lancun Rd", name:"Lancun Rd"},
        { index:"Langao Rd", name:"Langao Rd"},
        { index:"Laoximen", name:"Laoximen"},
        { index:"Lianhang Rd", name:"Lianhang Rd"},
        { index:"Lianhua Rd", name:"Lianhua Rd"},
        { index:"Lingang Avenue", name:"Lingang Avenue"},
        { index:"Lingkong Rd", name:"Lingkong Rd"},
        { index:"Lingzhao Xincun", name:"Lingzhao Xincun"},
        { index:"Linping Rd", name:"Linping Rd"},
        { index:"Linyi Xincun", name:"Linyi Xincun"},
        { index:"Liuhang", name:"Liuhang"},
        { index:"Liziyuan", name:"Liziyuan"},
        { index:"Longbai Xincun", name:"Longbai Xincun"},
        { index:"Longcao Rd", name:"Longcao Rd"},
        { index:"Longchang Rd", name:"Longchang Rd"},
        { index:"Longde Rd", name:"Longde Rd"},
        { index:"Longhua", name:"Longhua"},
        { index:"Longxi Rd", name:"Longxi Rd"},
        { index:"Longyang Rd", name:"Longyang Rd"},
        { index:"Longyao Rd", name:"Longyao Rd"},
        { index:"Loushanguan Rd", name:"Loushanguan Rd"},
        { index:"Luban Rd", name:"Luban Rd"},
        { index:"Luheng Rd", name:"Luheng Rd"},
        { index:"Lujiabang Rd", name:"Lujiabang Rd"},
        { index:"Lujiabang", name:"Lujiabang"},
        { index:"Lujiazui", name:"Lujiazui"},
        { index:"Luonan Xincun", name:"Luonan Xincun"},
        { index:"Luoshan Rd", name:"Luoshan Rd"},
        { index:"Madang Rd", name:"Madang Rd"},
        { index:"Malu", name:"Malu"},
        { index:"Meilan Lake", name:"Meilan Lake"},
        { index:"Middle Chuangxin Rd", name:"Middle Chuangxin Rd"},
        { index:"Middle Yanggao Rd", name:"Middle Yanggao Rd"},
        { index:"Middle Yanji Rd", name:"Middle Yanji Rd"},
        { index:"Minhang Development Zone", name:"Minhang Development Zone"},
        { index:"Minsheng Rd", name:"Minsheng Rd"},
        { index:"Nanchen Rd", name:"Nanchen Rd"},
        { index:"Nanpu Bridge", name:"Nanpu Bridge"},
        { index:"Nanxiang", name:"Nanxiang"},
        { index:"Nenjiang Rd", name:"Nenjiang Rd"},
        { index:"Ningguo Rd", name:"Ningguo Rd"},
        { index:"North Jiading", name:"North Jiading"},
        { index:"North Jiangyang Rd", name:"North Jiangyang Rd"},
        { index:"North Sichuan Rd", name:"North Sichuan Rd"},
        { index:"North Waigaoqiao Free Trade Zone", name:"North Waigaoqiao Free Trade Zone"},
        { index:"North Xizang Rd", name:"North Xizang Rd"},
        { index:"North Yanggao Rd", name:"North Yanggao Rd"},
        { index:"North Zhongshan Rd", name:"North Zhongshan Rd"},
        { index:"Oriental Sports Center", name:"Oriental Sports Center"},
        { index:"Panguang Rd", name:"Panguang Rd"},
        { index:"Pengpu Xincun", name:"Pengpu Xincun"},
        { index:"People's Square", name:"People's Square"},
        { index:"Pudian Rd", name:"Pudian Rd"},
        { index:"Pudong Avenue", name:"Pudong Avenue"},
        { index:"Pudong International Airport", name:"Pudong International Airport"},
        { index:"Pujiang Town", name:"Pujiang Town"},
        { index:"Pusan Rd", name:"Pusan Rd"},
        { index:"Qibao", name:"Qibao"},
        { index:"Qihua Rd", name:"Qihua Rd"},
        { index:"Qilianshan Rd", name:"Qilianshan Rd"},
        { index:"Qufu Rd", name:"Qufu Rd"},
        { index:"Quyang Rd", name:"Quyang Rd"},
        { index:"Sanlin", name:"Sanlin"},
        { index:"Sanmen Rd", name:"Sanmen Rd"},
        { index:"Shangcheng Rd", name:"Shangcheng Rd"},
        { index:"Shangda Rd", name:"Shangda Rd"},
        { index:"Shanghai Children's Medical Center", name:"Shanghai Children's Medical Center"},
        { index:"Shanghai Circuit", name:"Shanghai Circuit"},
        { index:"Shanghai Circus World", name:"Shanghai Circus World"},
        { index:"Shanghai Hongqiao Railway station", name:"Shanghai Hongqiao Railway station"},
        { index:"Shanghai Indoor Stadium", name:"Shanghai Indoor Stadium"},
        { index:"Shanghai Inte. Automobile City", name:"Shanghai Inte. Automobile City"},
        { index:"Shanghai Library", name:"Shanghai Library"},
        { index:"Shanghai Railway Station", name:"Shanghai Railway Station"},
        { index:"Shanghai Science and Technology Museum", name:"Shanghai Science and Technology Museum"},
        { index:"Shanghai South Railway Station", name:"Shanghai South Railway Station"},
        { index:"Shanghai Stadium", name:"Shanghai Stadium"},
        { index:"Shanghai Swimming Center", name:"Shanghai Swimming Center"},
        { index:"Shanghai University", name:"Shanghai University"},
        { index:"Shanghai Zoo", name:"Shanghai Zoo"},
        { index:"Shangnan Rd", name:"Shangnan Rd"},
        { index:"Shendu Highway", name:"Shendu Highway"},
        { index:"Shenjiang Rd", name:"Shenjiang Rd"},
        { index:"Sheshan", name:"Sheshan"},
        { index:"Shiguang Rd", name:"Shiguang Rd"},
        { index:"Shilong Rd", name:"Shilong Rd"},
        { index:"Shuichan Rd", name:"Shuichan Rd"},
        { index:"Shuicheng Rd", name:"Shuicheng Rd"},
        { index:"Shuyuan", name:"Shuyuan"},
        { index:"Sijing", name:"Sijing"},
        { index:"Siping Rd", name:"Siping Rd"},
        { index:"Songbin Rd", name:"Songbin Rd"},
        { index:"Songfa Rd", name:"Songfa Rd"},
        { index:"Songhong Rd", name:"Songhong Rd"},
        { index:"Songjiang South Railway Station", name:"Songjiang South Railway Station"},
        { index:"Songjiang Sports Center", name:"Songjiang Sports Center"},
        { index:"Songjiang University Town", name:"Songjiang University Town"},
        { index:"Songjiang Xincheng", name:"Songjiang Xincheng"},
        { index:"Songyuan Rd", name:"Songyuan Rd"},
        { index:"South Changjiang Rd", name:"South Changjiang Rd"},
        { index:"South Huangpi Rd", name:"South Huangpi Rd"},
        { index:"South Lingyan Rd", name:"South Lingyan Rd"},
        { index:"South Qilianshan Rd", name:"South Qilianshan Rd"},
        { index:"South Shaanxi Rd", name:"South Shaanxi Rd"},
        { index:"South Shanxi Rd", name:"South Shanxi Rd"},
        { index:"South Waigaoqiao Free Trade Zone", name:"South Waigaoqiao Free Trade Zone"},
        { index:"South Xizang Rd", name:"South Xizang Rd"},
        { index:"South Yanggao Rd", name:"South Yanggao Rd"},
        { index:"Tangqiao", name:"Tangqiao"},
        { index:"Tangzhen", name:"Tangzhen"},
        { index:"Taopu Xincun", name:"Taopu Xincun"},
        { index:"Tiantong Rd", name:"Tiantong Rd"},
        { index:"Tieli Rd", name:"Tieli Rd"},
        { index:"Tilanqiao", name:"Tilanqiao"},
        { index:"Tonghe Xincun", name:"Tonghe Xincun"},
        { index:"Tongji University", name:"Tongji University"},
        { index:"Waihuan Rd", name:"Waihuan Rd"},
        { index:"Wenshui Rd", name:"Wenshui Rd"},
        { index:"West Gaoke Rd", name:"West Gaoke Rd"},
        { index:"West Huaxia Rd", name:"West Huaxia Rd"},
        { index:"West Jiading", name:"West Jiading"},
        { index:"West Jinshajiang Rd", name:"West Jinshajiang Rd"},
        { index:"West Nanjing Rd", name:"West Nanjing Rd"},
        { index:"West Railway Station", name:"West Railway Station"},
        { index:"West Yan'an Rd", name:"West Yan'an Rd"},
        { index:"West Yingao Rd", name:"West Yingao Rd"},
        { index:"West Youyi Rd", name:"West Youyi Rd"},
        { index:"Wild Animal Park", name:"Wild Animal Park"},
        { index:"Wujiaochang", name:"Wujiaochang"},
        { index:"Wulian Rd", name:"Wulian Rd"},
        { index:"Wuning Rd", name:"Wuning Rd"},
        { index:"Wuwei Rd", name:"Wuwei Rd"},
        { index:"Wuzhou Avenue", name:"Wuzhou Avenue"},
        { index:"Xiangyin Rd", name:"Xiangyin Rd"},
        { index:"Xiaonanmen", name:"Xiaonanmen"},
        { index:"Xinchang", name:"Xinchang"},
        { index:"Xincun Rd", name:"Xincun Rd"},
        { index:"Xingzhi Rd", name:"Xingzhi Rd"},
        { index:"Xingzhong Rd", name:"Xingzhong Rd"},
        { index:"Xinjiangwancheng", name:"Xinjiangwancheng"},
        { index:"Xintiandi", name:"Xintiandi"},
        { index:"Xinzha Rd", name:"Xinzha Rd"},
        { index:"Xinzhuang", name:"Xinzhuang"},
        { index:"Xujiahui", name:"Xujiahui"},
        { index:"Yanchang Rd", name:"Yanchang Rd"},
        { index:"Yangshupu Rd", name:"Yangshupu Rd"},
        { index:"Yangsi", name:"Yangsi"},
        { index:"Yaohua Rd", name:"Yaohua Rd"},
        { index:"Yili Rd", name:"Yili Rd"},
        { index:"Yindu Rd", name:"Yindu Rd"},
        { index:"Yishan Rd", name:"Yishan Rd"},
        { index:"Youdian Xincun", name:"Youdian Xincun"},
        { index:"Youyi Rd", name:"Youyi Rd"},
        { index:"Yuandong Avenue", name:"Yuandong Avenue"},
        { index:"Yuanshen Stadium", name:"Yuanshen Stadium"},
        { index:"Yunjin Rd", name:"Yunjin Rd"},
        { index:"Yunshan Rd", name:"Yunshan Rd"},
        { index:"Yuntai Rd", name:"Yuntai Rd"},
        { index:"Yuqiao", name:"Yuqiao"},
        { index:"Yuyuan Garden", name:"Yuyuan Garden"},
        { index:"Zhanghuabang", name:"Zhanghuabang"},
        { index:"Zhangjiang High Technology Park", name:"Zhangjiang High Technology Park"},
        { index:"Zhaofeng Rd", name:"Zhaofeng Rd"},
        { index:"Zhaojiabang Rd", name:"Zhaojiabang Rd"},
        { index:"Zhenbei Rd", name:"Zhenbei Rd"},
        { index:"Zhenping Rd", name:"Zhenping Rd"},
        { index:"Zhenru", name:"Zhenru"},
        { index:"Zhongchun Rd", name:"Zhongchun Rd"},
        { index:"Zhongshan Park", name:"Zhongshan Park"},
        { index:"Zhongtan Rd", name:"Zhongtan Rd"},
        { index:"Zhongxing Rd", name:"Zhongxing Rd"},
        { index:"Zhouhai Rd", name:"Zhouhai Rd"},
        { index:"Zhuanqiao", name:"Zhuanqiao"},
        { index:"Ziteng Rd", name:"Ziteng Rd"},
        { index:"Zuibaichi Park", name:"Zuibaichi Park"}
    ]
});


