export default DS.Transform.extend({
  mapping : [
    { id: "Unknown", text: "Unknown 未知" },
    { id: "Student", text: "Student 学生" },
    { id: "Accountant", text: "Accountant 会计师" },
    { id: "Actor", text: "Actor 男演员" },
    { id: "Actress", text: "Actress 女演员" },
    { id: "Archaeologist", text: "Archaeologist 考古学家" },
    { id: "Architect", text: "Architect 建筑师" },
    { id: "Artists", text: "Artists 艺术家" },
    { id: "Astropologist", text: "Astropologist 人类学家" },
    { id: "Baker", text: "Baker 面包师" },
    { id: "Banker", text: "Banker 银行职员" },
    { id: "Biologist", text: "Biologist 生物学家" },
    { id: "Botanist", text: "Botanist 植物学家" },
    { id: "Car Mechanic", text: "Car Mechanic 汽车修理师" },
    { id: "Chemist", text: "Chemist 化学家" },
    { id: "Civil Planner", text: "Civil Planner 城市规划师" },
    { id: "Clerk", text: "Clerk 店员" },
    { id: "Composer", text: "Composer 作曲家" },
    { id: "Copywriter", text: "Copywriter 撰稿人" },
    { id: "Cosmetologist", text: "Cosmetologist 美容师" },
    { id: "Cutter", text: "Cutter 裁剪师" },
    { id: "Dancer", text: "Dancer 舞蹈家" },
    { id: "Dentist", text: "Dentist 牙科医生" },
    { id: "Designer (Graphic)", text: "Designer (Graphic) 平面设计师" },
    { id: "Designer (Interior Design)", text: "Designer (Interior Design) 室内设计师" },
    { id: "Designer (UI)", text: "Designer (UI) 界面设计师" },
    { id: "Designer (UX)", text: "Designer (UX) 用户体验设计师" },
    { id: "Designer (Fashion)", text: "Designer (Fashion) 时装设计师" },
    { id: "Director", text: "Director 导演" },
    { id: "Doctor", text: "Doctor 医生" },
    { id: "Dressmaker", text: "Dressmaker 女装裁剪师" },
    { id: "Economist", text: "Economist 经济学家" },
    { id: "Editor", text: "Editor 编辑" },
    { id: "Geologist", text: "Geologist 地址学家" },
    { id: "Government Officer", text: "Government Officer 公务员" },
    { id: "Guide", text: "Guide 导游" },
    { id: "Illustrator", text: "Illustrator 汇稿员" },
    { id: "Interpreter", text: "Interpreter 通译者" },
    { id: "Journalist", text: "Journalist 记者" },
    { id: "Linguist", text: "Linguist 语言学家" },
    { id: "Mathematician", text: "Mathematician 数学家" },
    { id: "Model", text: "Model 模特" },
    { id: "Musician", text: "Musician 音乐家" },
    { id: "Newscaster", text: "Newscaster 新闻评论人" },
    { id: "Novelist", text: "Novelist 小说家" },
    { id: "Nurse", text: "Nurse 护士" },
    { id: "Painter", text: "Painter 画家" },
    { id: "Pharmacist", text: "Pharmacist 药剂师" },
    { id: "Philosopher", text: "Philosopher 哲学家" },
    { id: "Photographer", text: "Photographer 摄影师" },
    { id: "Physicist", text: "Physicist 物理学家" },
    { id: "Physiologist", text: "Physiologist 生物学家" },
    { id: "Pilot", text: "Pilot 驾驶员" },
    { id: "Playwright", text: "Playwright 剧作家" },
    { id: "Poet", text: "Poet 诗人" },
    { id: "Policeman", text: "Policeman 警察" },
    { id: "Producer", text: "Producer 制片人" },
    { id: "Product Manager", text: "Product Manager 产品经理" },
    { id: "Programmer", text: "Programmer/IT 程序员" },
    { id: "Publisher", text: "Publisher 出版人员" },
    { id: "Receptionist", text: "Receptionist 接待员/前台" },
    { id: "Saleswoman", text: "Saleswoman 女店员" },
    { id: "Scholar", text: "Scholar 学者" },
    { id: "Scientist", text: "Scientist 科学家" },
    { id: "Sculptor", text: "Sculptor 雕刻家" },
    { id: "Secretary", text: "Secretary 秘书" },
    { id: "Sewer", text: "Sewer 裁缝师" },
    { id: "Shorthand Typist", text: "Shorthand Typist 速记打字员" },
    { id: "Simultaneous", text: "Simultaneous 传译员" },
    { id: "Singer", text: "Singer 歌手" },
    { id: "Statistician", text: "Statistician 统计学家" },
    { id: "Stenographer", text: "Stenographer 速记员" },
    { id: "Stewardess", text: "Stewardess 空姐" },
    { id: "System Analyst", text: "System Analyst 系统分析员" },
    { id: "Tailor", text: "Tailor 西装师傅" },
    { id: "Teacher", text: "Teacher 老师" },
    { id: "Telephone Operator", text: "Telephone Operator 电话接线员" },
    { id: "Tracer", text: "Tracer 绘图员" },
    { id: "Translator", text: "Translator 翻译家" }
  ]
});
